module.exports = {
  "Alberta": [
    "Calgary",
    "Edmonton",
    "Red Deer",
    "Lethbridge",
    "Medicine Hat",
    "Grande Prairie",
    "Airdrie",
    "Spruce Grove",
    "Leduc",
    "Lloydminster",
    "Camrose",
    "Fort McMurray",
    "Brooks",
    "Chestermere",
    "Okotoks",
    "St. Albert"
  ],
  "British Columbia": [
    "Vancouver",
    "Victoria",
    "Surrey",
    "Burnaby",
    "Kelowna",
    "Richmond",
    "Abbotsford",
    "Coquitlam",
    "Langley",
    "Nanaimo",
    "Kamloops",
    "Prince George",
    "Chilliwack",
    "Maple Ridge",
    "New Westminster",
    "Port Coquitlam",
    "North Vancouver",
    "West Vancouver",
    "Courtenay",
    "Vernon"
  ],
  "Manitoba": [
    "Winnipeg",
    "Brandon",
    "Steinbach",
    "Thompson",
    "Portage la Prairie",
    "Winkler",
    "Selkirk",
    "Dauphin",
    "Morden",
    "The Pas",
    "Flin Flon"
  ],
  "New Brunswick": [
    "Fredericton",
    "Moncton",
    "Saint John",
    "Miramichi",
    "Edmundston",
    "Bathurst",
    "Dieppe",
    "Campbellton",
    "Oromocto",
    "Woodstock"
  ],
  "Newfoundland and Labrador": [
    "St. John's",
    "Corner Brook",
    "Mount Pearl",
    "Gander",
    "Grand Falls-Windsor",
    "Labrador City",
    "Stephenville",
    "Clarenville",
    "Bay Roberts",
    "Marystown"
  ],
  "Northwest Territories": [
    "Yellowknife",
    "Hay River",
    "Inuvik",
    "Fort Smith",
    "Behchoko",
    "Tuktoyaktuk",
    "Norman Wells",
    "Fort Simpson",
    "Aklavik",
    "Fort Resolution"
  ],
  "Nova Scotia": [
    "Halifax",
    "Sydney",
    "Truro",
    "New Glasgow",
    "Kentville",
    "Amherst",
    "Bridgewater",
    "Yarmouth",
    "Antigonish",
    "Liverpool"
  ],
  "Nunavut": [
    "Iqaluit",
    "Rankin Inlet",
    "Arviat",
    "Baker Lake",
    "Cambridge Bay",
    "Igloolik",
    "Pond Inlet",
    "Cape Dorset",
    "Kugaaruk",
    "Clyde River"
  ],
  "Ontario": [
    "Toronto",
    "Ottawa",
    "Mississauga",
    "Brampton",
    "Hamilton",
    "London",
    "Markham",
    "Vaughan",
    "Kitchener",
    "Windsor",
    "Burlington",
    "Oakville",
    "Sudbury",
    "Barrie",
    "Kingston",
    "Guelph",
    "Thunder Bay",
    "Scarborough",
    "St. Catharines",
    "Cambridge",
    "Oshawa",
    "Richmond Hill",
    "Waterloo",
    "Pickering",
    "Ajax",
    "Whitby"
  ],
  "Prince Edward Island": [
    "Charlottetown",
    "Summerside",
    "Stratford",
    "Cornwall",
    "Montague",
    "Kensington",
    "Souris",
    "Alberton",
    "Tignish",
    "Georgetown"
  ],
  "Quebec": [
    "Montreal",
    "Quebec City",
    "Laval",
    "Gatineau",
    "Longueuil",
    "Sherbrooke",
    "Saguenay",
    "Levis",
    "Trois-Rivières",
    "Terrebonne",
    "Brossard",
    "Saint-Jean-sur-Richelieu",
    "Repentigny",
    "Drummondville",
    "Granby",
    "Blainville",
    "Saint-Jérôme",
    "Mascouche",
    "Rimouski"
  ],
  "Saskatchewan": [
    "Saskatoon",
    "Regina",
    "Prince Albert",
    "Moose Jaw",
    "Yorkton",
    "Swift Current",
    "North Battleford",
    "Estevan",
    "Weyburn",
    "Lloydminster"
  ],
  "Yukon": [
    "Whitehorse",
    "Dawson City",
    "Watson Lake",
    "Haines Junction",
    "Carcross",
    "Faro",
    "Carmacks",
    "Mayo",
    "Teslin",
    "Pelly Crossing"
  ]
};
